### ISSUE TITLE
Clang error

### ISSUE THREAD

**Issue by caspahouzer** [mikefogg/BarcodeView#3]
If I want to compile my app with this module and the 3.5.0.GA SDK, I got the following clang error:

```
[TRACE] Undefined symbols for architecture x86_64:
[TRACE]   "_OBJC_CLASS_$_ZBarImageScanner", referenced from:
[TRACE]       objc-class-ref in libcom.mfogg.barcode.a(ComMfoggBarcodeView.o)
[TRACE]   "_OBJC_CLASS_$_ZBarReaderView", referenced from:
[TRACE]       objc-class-ref in libcom.mfogg.barcode.a(ComMfoggBarcodeView.o)
[TRACE] ld: symbol(s) not found for architecture x86_64
[TRACE] clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Do you know how to solve this?

**Comment by caspahouzer** [comment]
Solved. I do a PR

**Comment by ghost** [comment]
Hey,

I am facing the same issue with 3.5.1.GA. How to solve this?

**Comment by mikefogg** [comment]
Hey @abhiit61, it looks like I was a bit behind but @caspahouzer was generous enough to do a pull request with the fix!! Just merged it into master :) You should be able to just pull it in and build now :)

Thanks @caspahouzer!
